name: 'Build and Deploy'

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to Server
        env:
          SSH_PORT: ${{ secrets.SSH_PORT }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
        run: |
          ssh -T -p "$SSH_PORT" "$SSH_USER@$SSH_HOST" << 'EOF' > /dev/null 2>&1
            cd lantern
            git pull origin main > /dev/null 2>&1
            npm install > /dev/null 2>&1
            npm run build > /dev/null 2>&1
            pm2 restart lantern > /dev/null 2>&1
          EOF

      - uses: chimpdev/bark-github-action@v1.0.1
        with:
            device_key: ${{ secrets.BARK_KEY }}
            server_url: ${{ secrets.BARK_SERVER_URL }}
            title: '${{ github.repository }}'
            body: 'Build and Deploy triggered and completed. Job is ${{ job.status }}.'
            url: '${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}'
            icon: 'https://i.ibb.co/7d8rL1c3/Git-Hub-Mark-ea2971cee799.jpg'
        if: always() # Run this step regardless of the outcome of previous steps