name: Label sync
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/labels.yml'
jobs:
  label-sync:
    name: Label sync
    runs-on: ubuntu-latest
    if: github.repository_owner == 'chimpdev'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Label sync
        uses: crazy-max/ghaction-github-labeler@v4
        with:
          github-token: ${{ secrets.GH_TOKEN }}